on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: go test -v -p=1 -timeout=0 ./...
    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        binary_name: "dpush"
        ldflags: "-s -w"
        extra_files: dpush_example.yaml